plugins:
  - jekyll-paginate

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginate_path: "page/:num"
baseurl: ""
url: ""

title: "小马飞奔"
email: xiaomafeibeng@gmail.com
description: "学习与生活，欢迎交流。"

github:
  username: xiaomafeibeng

swiftype:
  searchId:

comment:
  repo:
  client_id:
  client_secret:

imgrepo: "/static/img"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles: [highlight.css, post.css]
      scripts: [post.js]
